"""Criação do schema inicial de todas as tabelas

Revision ID: a75855aa7662
Revises: af762c79e1a4
Create Date: 2025-10-19 20:14:26.391618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a75855aa7662'
down_revision: Union[str, Sequence[str], None] = 'af762c79e1a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID interno sequencial do banco'),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='ID da liga na API, se disponível'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_name'), 'leagues', ['name'], unique=True)
    op.create_index(op.f('ix_leagues_source_id'), 'leagues', ['source_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_country', sa.String(length=255), nullable=True),
    sa.Column('nba_start_year', sa.Integer(), nullable=True),
    sa.Column('pro_years', sa.Integer(), nullable=True),
    sa.Column('height_meters', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('weight_kilograms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    op.create_index(op.f('ix_players_source_id'), 'players', ['source_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_nba_franchise', sa.Boolean(), nullable=True),
    sa.Column('is_all_star', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_code'), 'teams', ['code'], unique=False)
    op.create_index(op.f('ix_teams_source_id'), 'teams', ['source_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('visitor_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('visitor_score', sa.Integer(), nullable=True),
    sa.Column('home_linescore', sa.JSON(), nullable=True),
    sa.Column('visitor_linescore', sa.JSON(), nullable=True),
    sa.Column('arena_name', sa.String(length=255), nullable=True),
    sa.Column('arena_city', sa.String(length=255), nullable=True),
    sa.Column('arena_country', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.source_id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.source_id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['visitor_team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_index(op.f('ix_games_home_team_id'), 'games', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_games_league_id'), 'games', ['league_id'], unique=False)
    op.create_index(op.f('ix_games_season'), 'games', ['season'], unique=False)
    op.create_index(op.f('ix_games_source_id'), 'games', ['source_id'], unique=True)
    op.create_index(op.f('ix_games_visitor_team_id'), 'games', ['visitor_team_id'], unique=False)
    op.create_table('player_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=100), nullable=False),
    sa.Column('jersey', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'league_name', name='_player_league_uc')
    )
    op.create_index(op.f('ix_player_league_league_name'), 'player_league', ['league_name'], unique=False)
    op.create_index(op.f('ix_player_league_player_id'), 'player_league', ['player_id'], unique=False)
    op.create_table('standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('conference_name', sa.String(length=100), nullable=True),
    sa.Column('conference_rank', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.String(length=100), nullable=True),
    sa.Column('division_rank', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('games_behind', sa.String(length=10), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=True),
    sa.Column('win_streak', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False, comment='ID original da fonte de dados externa (API)'),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False, comment='Hash SHA-256 do payload da API para detecção de mudanças'),
    sa.Column('is_active', sa.Integer(), nullable=False, comment='Indica se o registro está ativo (1) ou inativo (0)'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.source_id'], ),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('league_id', 'season', 'team_id', name='_league_season_team_uc')
    )
    op.create_table('team_league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=100), nullable=False),
    sa.Column('conference', sa.String(length=100), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'league_name', name='_team_league_uc')
    )
    op.create_index(op.f('ix_team_league_league_name'), 'team_league', ['league_name'], unique=False)
    op.create_index(op.f('ix_team_league_team_id'), 'team_league', ['team_id'], unique=False)
    op.create_table('team_season_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('fast_break_points', sa.Integer(), nullable=True),
    sa.Column('points_in_paint', sa.Integer(), nullable=True),
    sa.Column('biggest_lead', sa.Integer(), nullable=True),
    sa.Column('second_chance_points', sa.Integer(), nullable=True),
    sa.Column('points_off_turnovers', sa.Integer(), nullable=True),
    sa.Column('longest_run', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['season'], ['seasons.season'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', name='_team_season_uc')
    )
    op.create_index(op.f('ix_team_season_statistics_season'), 'team_season_statistics', ['season'], unique=False)
    op.create_index(op.f('ix_team_season_statistics_team_id'), 'team_season_statistics', ['team_id'], unique=False)
    op.create_table('player_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('min_played', sa.String(length=10), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.String(length=10), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.source_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='_player_game_uc')
    )
    op.create_index(op.f('ix_player_statistics_game_id'), 'player_statistics', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_statistics_player_id'), 'player_statistics', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_statistics_team_id'), 'player_statistics', ['team_id'], unique=False)
    op.create_table('team_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('fast_break_points', sa.Integer(), nullable=True),
    sa.Column('points_in_paint', sa.Integer(), nullable=True),
    sa.Column('biggest_lead', sa.Integer(), nullable=True),
    sa.Column('second_chance_points', sa.Integer(), nullable=True),
    sa.Column('points_off_turnovers', sa.Integer(), nullable=True),
    sa.Column('longest_run', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fgm', sa.Integer(), nullable=True),
    sa.Column('fga', sa.Integer(), nullable=True),
    sa.Column('fgp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ftm', sa.Integer(), nullable=True),
    sa.Column('fta', sa.Integer(), nullable=True),
    sa.Column('ftp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('tpa', sa.Integer(), nullable=True),
    sa.Column('tpp', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('off_reb', sa.Integer(), nullable=True),
    sa.Column('def_reb', sa.Integer(), nullable=True),
    sa.Column('tot_reb', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('p_fouls', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('plus_minus', sa.String(length=10), nullable=True),
    sa.Column('min_played', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.source_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.source_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='_game_team_uc')
    )
    op.create_index(op.f('ix_team_statistics_game_id'), 'team_statistics', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_statistics_team_id'), 'team_statistics', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_statistics_team_id'), table_name='team_statistics')
    op.drop_index(op.f('ix_team_statistics_game_id'), table_name='team_statistics')
    op.drop_table('team_statistics')
    op.drop_index(op.f('ix_player_statistics_team_id'), table_name='player_statistics')
    op.drop_index(op.f('ix_player_statistics_player_id'), table_name='player_statistics')
    op.drop_index(op.f('ix_player_statistics_game_id'), table_name='player_statistics')
    op.drop_table('player_statistics')
    op.drop_index(op.f('ix_team_season_statistics_team_id'), table_name='team_season_statistics')
    op.drop_index(op.f('ix_team_season_statistics_season'), table_name='team_season_statistics')
    op.drop_table('team_season_statistics')
    op.drop_index(op.f('ix_team_league_team_id'), table_name='team_league')
    op.drop_index(op.f('ix_team_league_league_name'), table_name='team_league')
    op.drop_table('team_league')
    op.drop_table('standings')
    op.drop_index(op.f('ix_player_league_player_id'), table_name='player_league')
    op.drop_index(op.f('ix_player_league_league_name'), table_name='player_league')
    op.drop_table('player_league')
    op.drop_index(op.f('ix_games_visitor_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_source_id'), table_name='games')
    op.drop_index(op.f('ix_games_season'), table_name='games')
    op.drop_index(op.f('ix_games_league_id'), table_name='games')
    op.drop_index(op.f('ix_games_home_team_id'), table_name='games')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_source_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_players_source_id'), table_name='players')
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_leagues_source_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_name'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
